# Redis configuration values
replica:
  replicas: 1

service:
  name: redis
  type: ClusterIP
  port: 6379
  targetPort: 6379

resources:
  maxmem: 500M

port: 6379

image: 
  name: redis
  version: latest

affinity:
  node: "kind-control-plane"  

persistence:
  enabled: true
  storageClass: "local-storage"
  size: 800M